### ISSUE TITLE
TypeError: port must be an integer

### ISSUE THREAD

**Issue by matheuschagas** [Livin21/LinuxDrop#7]
this is the output:

`Starting thrusters...
Launching EliStories.mp4 to outer space...
Traceback (most recent call last):
  File "/usr/local/bin/lidrop", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/lidrop.py", line 12, in run
    send.start_server(f_name)
  File "/usr/local/lib/python2.7/dist-packages/sender/send.py", line 47, in start_server
    app.run("0.0.0.0", "1921")
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 748, in run_simple
    raise TypeError('port must be an integer')
TypeError: port must be an integer
`

**Comment by Livin21** [comment]
I'll look into it
